<?php
/**
 * AQUÍ VA LO RELACIONADO CON EL PERFIL DE ADMINISTRADOR:
 * SE CREA UNA CUENTA EN LA BASE DE DATOS
 * ESTA PÁGINA QUEDA OCULTA, SÓLO QUIENES CONOCEN el nombre del mismo lo saben
 * UNA VEZ QUE EL ADMINISTRADOR ENTRA CON SU CUENTA, TENDRÁ LOS PROVOLEGIOS DE
 * ELIMINAR, EDITAR CONSULTAR Y AÑADIR USUARIO SIEMPRE QUE NECESITE
 * 
 * UNA PREGUNTA PARA JERO: CON AUTOLOAD, ¿ES POSIBLE EN PHP UTILIZAR HEADER Y ENTRE COMILLAS
 * PONER LA PALABRA CLAVE PARA REDIRIGIRSE CON INDEX.PHP?
 */
?>